# 云函数
# https://github.com/serverless-components/tencent-scf/blob/v2/doc/serverless.yaml

org: offcn-jl
app: serverless-apis
component: scf
name: scf-sso-v2-send-v-code
stage: dev

inputs:
  name: ${org}-${app}-${name}-${stage}
  description: 单点登陆 - 验证码 - 发送
  enableRoleAuth: true
  src: ./artifacts
  handler: main
  runtime: Go1
  region: ${env:REGION}
  memorySize: 64
  timeout: 5
  vpcConfig:
    vpcId: ${env:VPC_ID}
    subnetId: ${env:SUBNET_ID}
  environment:
    variables:
      Debug: ${env:DEBUG}
      PostgreSQLHost: ${output:${stage}:${app}:postgre-sql.private.host}
      PostgreSQLPort: ${output:${stage}:${app}:postgre-sql.private.port}
      PostgreSQLUser: ${output:${stage}:${app}:postgre-sql.private.user}
      PostgreSQLDBName: ${output:${stage}:${app}:postgre-sql.private.dbname}
      PostgreSQLPassword: ${output:${stage}:${app}:postgre-sql.private.password}
      PostgreSQLSSLMode: disable
      OFFCN_SMS_URL: ${env:OFFCN_SMS_URL}
      OFFCN_SMS_NAME: ${env:OFFCN_SMS_NAME}
      OFFCN_SMS_PWD: ${env:OFFCN_SMS_PWD}
      OFFCN_SMS_TJ_Code: ${env:OFFCN_SMS_TJ_Code}
      TENCENT_SECRET_ID: ${env:TENCENT_SECRET_ID}
      TENCENT_SECRET_KEY: ${env:TENCENT_SECRET_KEY}
      TENCENT_SMS_APPID: ${env:TENCENT_SMS_APPID}
  events:
    - apigw:
        parameters:
          serviceId: ${env:APIGW_SERVICE_ID}
          protocols:
            - https
          environment: ${env:APIGW_ENV}
          endpoints:
            - path: /sso/v2/verification-code/send/{MID}/{Phone}
              method: POST
              enableCORS: FALSE
              responseType: JSON
              serviceTimeout: 10
              param:
                - name: MID
                  position: PATH
                  required: 'TRUE'
                  type: int
                  desc: 登陆模块 ID
                - name: Phone
                  position: PATH
                  required: 'TRUE'
                  type: int
                  desc: 手机号码
              function:
                isIntegratedResponse: TRUE
                functionQualifier: $LATEST
