# 云函数
# https://github.com/serverless-components/tencent-scf/blob/v2/doc/serverless.yaml

org: offcn-jl
app: serverless-apis
component: scf
name: scf-sso-v2-suffix-list
stage: dev

inputs:
  name: ${org}-${app}-${name}-${stage}
  description: 单点登陆 - 认证 - 注册
  enableRoleAuth: true
  src: ./artifacts
  handler: main
  runtime: Go1
  region: ${env:REGION}
  memorySize: 64
  timeout: 5
  vpcConfig:
    vpcId: ${env:VPC_ID}
    subnetId: ${env:SUBNET_ID}
  environment:
    variables:
      Debug: ${env:DEBUG}
      PostgreSQLHost: ${output:${stage}:${app}:postgre-sql.private.host}
      PostgreSQLPort: ${output:${stage}:${app}:postgre-sql.private.port}
      PostgreSQLUser: ${output:${stage}:${app}:postgre-sql.private.user}
      PostgreSQLDBName: ${output:${stage}:${app}:postgre-sql.private.dbname}
      PostgreSQLPassword: ${output:${stage}:${app}:postgre-sql.private.password}
      PostgreSQLSSLMode: disable
  events:
    - apigw:
        parameters:
          serviceId: ${env:APIGW_SERVICE_ID}
          protocols:
            - https
          environment: ${env:APIGW_ENV}
          endpoints:
            - path: /sso/v2/suffix/list
              method: GET
              enableCORS: FALSE
              responseType: JSON
              serviceTimeout: 10
              function:
                isIntegratedResponse: TRUE
                functionQualifier: $LATEST
