# 云函数
# https://github.com/serverless-components/tencent-scf/blob/v2/doc/configure.md

org: offcn-jl
app: serverless-apis
component: scf
name: A2020GiftCheckout
stage: test

inputs:
  name: ${org}-${app}-${name}-${stage}
  description: 2020 - 礼品 - 查询获奖信息 # 描述
  enableRoleAuth: true # 启用角色和策略
  src: ./artifacts
  handler: main # 入口
  runtime: Go1 # 运行环境
  region: ${env:REGION} # 地域
  memorySize: 64 # 内存大小
  timeout: 120 # 超时时间
  environment: # 环境变量
    variables: # 环境变量数组
      PostgreSQLHost: ${output:${stage}:${app}:postgre-sql.public.host}
      PostgreSQLPort: ${output:${stage}:${app}:postgre-sql.public.port}
      PostgreSQLUser: ${output:${stage}:${app}:postgre-sql.public.user}
      PostgreSQLDBName: ${output:${stage}:${app}:postgre-sql.public.dbname}
      PostgreSQLPassword: ${output:${stage}:${app}:postgre-sql.public.password}
      PostgreSQLSSLMode: disable
  events:
    - apigw:
        name: ${org}-${app}-${name}-${stage}
        parameters:
          serviceId: service-6ej2uglf
          protocols:
            - https
          environment: ${stage}
          endpoints:
            - path: /2020/gift/{Name}/checkout/{Phone}
              method: GET
              enableCORS: FALSE
              responseType: JSON
              serviceTimeout: 120
              param:
                - name: Name
                  position: PATH
                  required: 'TRUE'
                  type: string
                  desc: 奖品名称
                - name: Phone
                  position: PATH
                  required: 'TRUE'
                  type: int
                  desc: 手机号码
              function:
                isIntegratedResponse: TRUE
                functionQualifier: $LATEST
