# 云函数
# https://github.com/serverless-components/tencent-scf/blob/v2/doc/serverless.yaml

org: offcn-jl
app: serverless-apis
component: scf
name: scf-get-app-version-info
stage: dev

inputs:
  name: ${org}-${app}-${name}-${stage}
  description: 应用 - 版本控制 - 版本 - 获取信息 # 描述
  enableRoleAuth: true # 启用角色和策略
  src: ./artifacts
  handler: main # 入口
  runtime: Go1 # 运行环境
  region: ${env:REGION} # 地域
  memorySize: 64 # 内存大小
  timeout: 5 # 超时时间
  vpcConfig:
    vpcId: ${env:VPC_ID}
    subnetId: ${env:SUBNET_ID}
  environment: # 环境变量
    variables: # 环境变量数组
      PostgreSQLHost: ${output:${stage}:${app}:postgre-sql.private.host}
      PostgreSQLPort: ${output:${stage}:${app}:postgre-sql.private.port}
      PostgreSQLUser: ${output:${stage}:${app}:postgre-sql.private.user}
      PostgreSQLDBName: ${output:${stage}:${app}:postgre-sql.private.dbname}
      PostgreSQLPassword: ${output:${stage}:${app}:postgre-sql.private.password}
      PostgreSQLSSLMode: disable
      Debug: ${env:DEBUG}
  events:
    - apigw:
        parameters:
          serviceId: ${env:APIGW_SERVICE_ID}
          protocols:
            - https
          environment: ${env:APIGW_ENV}
          endpoints:
            - path: /app/version-control/version/get/{AppID}
              method: GET
              # description: 应用 - 版本控制 - 版本 - 获取信息 # 描述
              enableCORS: FALSE
              responseType: JSON
              serviceTimeout: 10
              param:
                - name: AppID
                  position: PATH
                  required: 'TRUE'
                  type: string
                  desc: 应用ID
              function:
                isIntegratedResponse: TRUE
                functionQualifier: $LATEST
