name: Master Build

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Remove go mod replaces # 参考 https://blog.vgmdj.cn/post/go%E8%AF%AD%E8%A8%80%E5%AD%A6%E4%B9%A0-module%E6%9C%BA%E5%88%B6/
      run: |
        workspace=$(pwd)
        cd base-on-serverless
        go mod edit -dropreplace=github.com/offcn-jl/gscf
        go mod edit -dropreplace=github.com/offcn-jl/go-common
        cd ${workspace}
        cd base-on-tsf
        go mod edit -dropreplace=github.com/offcn-jl/go-common

#    - name: Commit go mod # 将移除 replace 的 go mod 进行提交 -> 规划中, 目前存在的问题是使用 git 命令行需要自行配置 git , 环境中的 git 是未配置的
#      run: |
#        git add */go.mod
#        git commit -m "Github Action > Remove go mod replaces"

    - name: Get dependencies
      run: |
        workspace=$(pwd)
        cd base-on-serverless
        go mod download
        cd ${workspace}
        cd base-on-tsf
        go mod download

#    - name: Build # 编译测试流程 -> 规划中
#      run: go build -v .

    - name: Test
      run: |
        workspace=$(pwd)
        cd base-on-serverless
        go test ./... -race -coverprofile=coverage.txt -covermode=atomic
        cd ${workspace}
        cd base-on-tsf
        go test ./... -race -coverprofile=coverage.txt -covermode=atomic

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.6
      with:
        token: ${{secrets.CODECOV_TOKEN}}

#    - name: Push go mod # 将移除 replace 的 go mod 进行推送 -> 规划中
#      run: git push
